services:
  - type: web
    name: sixm-backend
    env: python
    plan: free
    buildCommand: "pip install pipenv && pipenv install"
    startCommand: "pipenv run gunicorn -w 4 -b 0.0.0.0:5000 run:app"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///instance/hardware_app.db"
